<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <DefaultItemExcludes>$(DefaultItemExcludes);EsportTeamManager.Application\**;EsportTeamManager.Domain\**;EsportTeamManager.Infrastructure\**;EsportTeamManager.Infrastructure.PostgreSql.Migrations\**;EsportTeamManager.Tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="EsportTeamManager.Infrastructure.PostgreSql.Migrations\EsportTeamManager.Infrastructure.PostgreSql.Migrations.csproj" />
    <ProjectReference Include="EsportTeamManager.Application\EsportTeamManager.Application.csproj" />
    <ProjectReference Include="EsportTeamManager.Infrastructure\EsportTeamManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
