// <auto-generated />
using System;
using EsportTeamManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsportTeamManager.Infrastructure.PostgreSql.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260825201423_AddPendingEmailReservationConstraints")]
    partial class AddPendingEmailReservationConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActionTrace", b =>
                {
                    b.Property<Guid>("ActionTraceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("ActionTraceId");

                    b.HasIndex("ActionCode")
                        .HasDatabaseName("IX_ActionTraces_ActionCode");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_ActionTraces_ExpiresAtUtc");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_ActionTraces_OccurredAtUtc");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_ActionTraces_TeamId");

                    b.ToTable("ActionTraces", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActionTraces_Expiration", "\"ExpiresAtUtc\" > \"OccurredAtUtc\"");

                            t.HasCheckConstraint("CK_ActionTraces_Outcome", "\"Outcome\" IN ('Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActivityLink", b =>
                {
                    b.Property<Guid>("ActivityLinkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("ActivityLinkId");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("IX_ActivityLinks_ActivityId");

                    b.ToTable("ActivityLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActivityLinks_Url", "LOWER(\"Url\") LIKE 'http://%' OR LOWER(\"Url\") LIKE 'https://%'");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActivityParticipant", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Attendance")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("ActivityId", "TeamMembershipId");

                    b.HasIndex("TeamMembershipId")
                        .HasDatabaseName("IX_ActivityParticipants_TeamMembershipId");

                    b.ToTable("ActivityParticipants", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActivityParticipants_Attendance", "\"Attendance\" IS NULL OR \"Attendance\" IN ('Present', 'Absent')");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActivityStrategy", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivityId", "StrategyId");

                    b.HasIndex("StrategyId");

                    b.ToTable("ActivityStrategies", (string)null);
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActivityType", b =>
                {
                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivityTypeId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ActivityTypes_SystemCode")
                        .HasFilter("\"TeamId\" IS NULL");

                    b.HasIndex("TeamId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ActivityTypes_TeamId_Code")
                        .HasFilter("\"TeamId\" IS NOT NULL");

                    b.ToTable("ActivityTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActivityTypes_SystemOwnership", "(\"IsSystem\" = TRUE AND \"TeamId\" IS NULL) OR (\"IsSystem\" = FALSE AND \"TeamId\" IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            ActivityTypeId = 1,
                            Code = "Pracc",
                            IsSystem = true,
                            Label = "Pracc"
                        },
                        new
                        {
                            ActivityTypeId = 2,
                            Code = "OfficialMatch",
                            IsSystem = true,
                            Label = "Match officiel"
                        },
                        new
                        {
                            ActivityTypeId = 3,
                            Code = "Meeting",
                            IsSystem = true,
                            Label = "Réunion"
                        },
                        new
                        {
                            ActivityTypeId = 4,
                            Code = "VodReview",
                            IsSystem = true,
                            Label = "Review VOD"
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.FormerMember", b =>
                {
                    b.Property<Guid>("FormerMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocalNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("FormerMemberId");

                    b.HasIndex("TeamId", "LocalNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_FormerMembers_TeamId_LocalNumber");

                    b.ToTable("FormerMembers", null, t =>
                        {
                            t.HasCheckConstraint("CK_FormerMembers_LocalNumber", "\"LocalNumber\" > 0");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ImageFile", b =>
                {
                    b.Property<Guid>("ImageFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("HeightPixels")
                        .HasColumnType("integer");

                    b.Property<string>("InternalFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OptimizedStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("StrategyImageForStrategyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamLogoForTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("WidthPixels")
                        .HasColumnType("integer");

                    b.HasKey("ImageFileId");

                    b.HasIndex("InternalFileName")
                        .IsUnique()
                        .HasDatabaseName("UX_ImageFiles_InternalFileName");

                    b.HasIndex("OptimizedStorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ImageFiles_OptimizedStorageKey");

                    b.HasIndex("StrategyImageForStrategyId")
                        .IsUnique()
                        .HasDatabaseName("UX_ImageFiles_StrategyImageForStrategyId")
                        .HasFilter("\"StrategyImageForStrategyId\" IS NOT NULL");

                    b.HasIndex("TeamLogoForTeamId")
                        .IsUnique()
                        .HasDatabaseName("UX_ImageFiles_TeamLogoForTeamId")
                        .HasFilter("\"TeamLogoForTeamId\" IS NOT NULL");

                    b.HasIndex("ThumbnailStorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ImageFiles_ThumbnailStorageKey");

                    b.ToTable("ImageFiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImageFiles_FileSizeBytes", "\"FileSizeBytes\" > 0");

                            t.HasCheckConstraint("CK_ImageFiles_HeightPixels", "\"HeightPixels\" > 0");

                            t.HasCheckConstraint("CK_ImageFiles_MediaType", "\"MediaType\" IN ('image/png', 'image/jpeg', 'image/webp')");

                            t.HasCheckConstraint("CK_ImageFiles_Owner", "(\"TeamLogoForTeamId\" IS NOT NULL AND \"StrategyImageForStrategyId\" IS NULL) OR (\"TeamLogoForTeamId\" IS NULL AND \"StrategyImageForStrategyId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ImageFiles_WidthPixels", "\"WidthPixels\" > 0");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedMembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProposedTeamRoleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("InvitationId");

                    b.HasIndex("CreatedMembershipId");

                    b.HasIndex("ProposedTeamRoleId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("RecipientUserId", "Status")
                        .HasDatabaseName("IX_Invitations_RecipientUserId_Status");

                    b.HasIndex("TeamId", "RecipientUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Invitations_PendingRecipient")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("TeamId", "Status")
                        .HasDatabaseName("IX_Invitations_TeamId_Status");

                    b.ToTable("Invitations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invitations_CreatedMembership", "(\"Status\" = 'Accepted' AND \"CreatedMembershipId\" IS NOT NULL) OR (\"Status\" <> 'Accepted' AND \"CreatedMembershipId\" IS NULL)");

                            t.HasCheckConstraint("CK_Invitations_Resolution", "(\"Status\" = 'Pending' AND \"ResolvedAtUtc\" IS NULL) OR (\"Status\" <> 'Pending' AND \"ResolvedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Invitations_ResolvedAtUtc", "\"ResolvedAtUtc\" IS NULL OR \"ResolvedAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_Invitations_Status", "\"Status\" IN ('Pending', 'Accepted', 'Refused', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.LegalAcceptance", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("LegalDocumentVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "LegalDocumentVersionId");

                    b.HasIndex("LegalDocumentVersionId");

                    b.ToTable("LegalAcceptances", (string)null);
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.LegalDocumentVersion", b =>
                {
                    b.Property<int>("LegalDocumentVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresAcceptance")
                        .HasColumnType("boolean");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("LegalDocumentVersionId");

                    b.HasIndex("DocumentType", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_LegalDocumentVersions_DocumentType_VersionNumber");

                    b.ToTable("LegalDocumentVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_LegalDocumentVersions_DocumentType", "\"DocumentType\" IN ('TermsOfService', 'PrivacyPolicy')");
                        });

                    b.HasData(
                        new
                        {
                            LegalDocumentVersionId = 1,
                            DocumentType = "TermsOfService",
                            PublishedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RequiresAcceptance = true,
                            VersionNumber = "1.0"
                        },
                        new
                        {
                            LegalDocumentVersionId = 2,
                            DocumentType = "PrivacyPolicy",
                            PublishedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RequiresAcceptance = false,
                            VersionNumber = "1.0"
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.Map", b =>
                {
                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MapId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Maps_Name");

                    b.ToTable("Maps", (string)null);

                    b.HasData(
                        new
                        {
                            MapId = 1,
                            Name = "Bind"
                        },
                        new
                        {
                            MapId = 2,
                            Name = "Haven"
                        },
                        new
                        {
                            MapId = 3,
                            Name = "Split"
                        },
                        new
                        {
                            MapId = 4,
                            Name = "Ascent"
                        },
                        new
                        {
                            MapId = 5,
                            Name = "Icebox"
                        },
                        new
                        {
                            MapId = 6,
                            Name = "Breeze"
                        },
                        new
                        {
                            MapId = 7,
                            Name = "Fracture"
                        },
                        new
                        {
                            MapId = 8,
                            Name = "Pearl"
                        },
                        new
                        {
                            MapId = 9,
                            Name = "Lotus"
                        },
                        new
                        {
                            MapId = 10,
                            Name = "Sunset"
                        },
                        new
                        {
                            MapId = 11,
                            Name = "Abyss"
                        },
                        new
                        {
                            MapId = 12,
                            Name = "Corrode"
                        },
                        new
                        {
                            MapId = 13,
                            Name = "Summit"
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.MatchDetail", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("OpponentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OpponentScore")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamScore")
                        .HasColumnType("integer");

                    b.HasKey("ActivityId");

                    b.ToTable("MatchDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_MatchDetails_CompleteScore", "(\"TeamScore\" IS NULL AND \"OpponentScore\" IS NULL) OR (\"TeamScore\" IS NOT NULL AND \"OpponentScore\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_MatchDetails_OpponentScore", "\"OpponentScore\" IS NULL OR \"OpponentScore\" >= 0");

                            t.HasCheckConstraint("CK_MatchDetails_TeamScore", "\"TeamScore\" IS NULL OR \"TeamScore\" >= 0");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnershipTransferId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId");

                    b.HasIndex("InvitationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Notifications_InvitationId")
                        .HasFilter("\"InvitationId\" IS NOT NULL");

                    b.HasIndex("OwnershipTransferId")
                        .IsUnique()
                        .HasDatabaseName("UX_Notifications_OwnershipTransferId")
                        .HasFilter("\"OwnershipTransferId\" IS NOT NULL");

                    b.HasIndex("RecipientUserId", "ReadAtUtc")
                        .HasDatabaseName("IX_Notifications_RecipientUserId_ReadAtUtc");

                    b.ToTable("Notifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_ReadAtUtc", "\"ReadAtUtc\" IS NULL OR \"ReadAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_Notifications_Source", "(\"InvitationId\" IS NOT NULL AND \"OwnershipTransferId\" IS NULL) OR (\"InvitationId\" IS NULL AND \"OwnershipTransferId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.OwnershipTransfer", b =>
                {
                    b.Property<Guid>("OwnershipTransferId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatorMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipientMembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("OwnershipTransferId");

                    b.HasIndex("InitiatorMembershipId");

                    b.HasIndex("RecipientMembershipId");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("UX_OwnershipTransfers_PendingTeam")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("TeamId", "Status")
                        .HasDatabaseName("IX_OwnershipTransfers_TeamId_Status");

                    b.ToTable("OwnershipTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_OwnershipTransfers_Memberships", "\"InitiatorMembershipId\" <> \"RecipientMembershipId\"");

                            t.HasCheckConstraint("CK_OwnershipTransfers_Resolution", "(\"Status\" = 'Pending' AND \"ResolvedAtUtc\" IS NULL) OR (\"Status\" <> 'Pending' AND \"ResolvedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_OwnershipTransfers_ResolvedAtUtc", "\"ResolvedAtUtc\" IS NULL OR \"ResolvedAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_OwnershipTransfers_Status", "\"Status\" IN ('Pending', 'Accepted', 'Refused', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ReservedIdentity", b =>
                {
                    b.Property<string>("IdentityHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ReservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdentityHash");

                    b.ToTable("ReservedIdentities", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReservedIdentities_IdentityHash", "LENGTH(\"IdentityHash\") = 64");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.Strategy", b =>
                {
                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StrategyId");

                    b.HasIndex("CreatedByMembershipId");

                    b.HasIndex("MapId")
                        .HasDatabaseName("IX_Strategies_MapId");

                    b.HasIndex("Side")
                        .HasDatabaseName("IX_Strategies_Side");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("IX_Strategies_UpdatedAtUtc");

                    b.HasIndex("TeamId", "IsActive")
                        .HasDatabaseName("IX_Strategies_TeamId_IsActive");

                    b.ToTable("Strategies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Strategies_ExternalUrl", "\"ExternalUrl\" IS NULL OR LOWER(\"ExternalUrl\") LIKE 'http://%' OR LOWER(\"ExternalUrl\") LIKE 'https://%'");

                            t.HasCheckConstraint("CK_Strategies_Side", "\"Side\" IN ('Attack', 'Defense')");

                            t.HasCheckConstraint("CK_Strategies_UpdatedAtUtc", "\"UpdatedAtUtc\" >= \"CreatedAtUtc\"");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeletedMemberCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("TeamId");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_Teams_OwnerUserId");

                    b.ToTable("Teams", null, t =>
                        {
                            t.HasCheckConstraint("CK_Teams_DeletedMemberCounter", "\"DeletedMemberCounter\" >= 0");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.TeamActivity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("PlannedEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlannedStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Report")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityTypeId")
                        .HasDatabaseName("IX_Activities_ActivityTypeId");

                    b.HasIndex("CreatedByMembershipId");

                    b.HasIndex("TeamId", "PlannedStartUtc")
                        .HasDatabaseName("IX_Activities_TeamId_PlannedStartUtc");

                    b.HasIndex("TeamId", "Status")
                        .HasDatabaseName("IX_Activities_TeamId_Status");

                    b.ToTable("Activities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Activities_CancellationReason", "\"Status\" = 'Cancelled' OR \"CancellationReason\" IS NULL");

                            t.HasCheckConstraint("CK_Activities_Schedule", "\"PlannedEndUtc\" > \"PlannedStartUtc\"");

                            t.HasCheckConstraint("CK_Activities_Status", "\"Status\" IN ('Planned', 'Completed', 'Cancelled')");

                            t.HasCheckConstraint("CK_Activities_UpdatedAtUtc", "\"UpdatedAtUtc\" >= \"CreatedAtUtc\"");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.TeamMembership", b =>
                {
                    b.Property<Guid>("TeamMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FormerMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeftAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamRoleId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamMembershipId");

                    b.HasIndex("FormerMemberId");

                    b.HasIndex("TeamRoleId");

                    b.HasIndex("TeamId", "Status")
                        .HasDatabaseName("IX_TeamMemberships_TeamId_Status");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_TeamMemberships_ActiveUser")
                        .HasFilter("\"Status\" = 'Active' AND \"UserId\" IS NOT NULL");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_TeamMemberships_UserId_Status");

                    b.ToTable("TeamMemberships", null, t =>
                        {
                            t.HasCheckConstraint("CK_TeamMemberships_Closure", "(\"Status\" = 'Active' AND \"LeftAtUtc\" IS NULL) OR (\"Status\" IN ('Left', 'Removed') AND \"LeftAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_TeamMemberships_Holder", "(\"UserId\" IS NOT NULL AND \"FormerMemberId\" IS NULL) OR (\"UserId\" IS NULL AND \"FormerMemberId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_TeamMemberships_LeftAtUtc", "\"LeftAtUtc\" IS NULL OR \"LeftAtUtc\" >= \"JoinedAtUtc\"");

                            t.HasCheckConstraint("CK_TeamMemberships_Status", "\"Status\" IN ('Active', 'Left', 'Removed')");
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.TeamRole", b =>
                {
                    b.Property<int>("TeamRoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamRoleId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_TeamRoles_SystemCode")
                        .HasFilter("\"TeamId\" IS NULL");

                    b.HasIndex("TeamId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_TeamRoles_TeamId_Code")
                        .HasFilter("\"TeamId\" IS NOT NULL");

                    b.ToTable("TeamRoles", null, t =>
                        {
                            t.HasCheckConstraint("CK_TeamRoles_SystemOwnership", "(\"IsSystem\" = TRUE AND \"TeamId\" IS NULL) OR (\"IsSystem\" = FALSE AND \"TeamId\" IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            TeamRoleId = 1,
                            Code = "Manager",
                            IsSystem = true,
                            Label = "Manager"
                        },
                        new
                        {
                            TeamRoleId = 2,
                            Code = "Coach",
                            IsSystem = true,
                            Label = "Coach"
                        },
                        new
                        {
                            TeamRoleId = 3,
                            Code = "Player",
                            IsSystem = true,
                            Label = "Joueur"
                        });
                });

            modelBuilder.Entity("EsportTeamManager.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTimeOffset?>("EmailConfirmationSentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MinimumAgeDeclaredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("NormalizedPendingEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("PasswordResetEmailCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PasswordResetEmailWindowStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTimeOffset?>("PendingEmailExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedPendingEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_AspNetUsers_NormalizedPendingEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_AccountStatus", "\"AccountStatus\" IN ('PendingConfirmation', 'Active', 'Suspended')");

                            t.HasCheckConstraint("CK_AspNetUsers_PasswordResetEmailCount", "\"PasswordResetEmailCount\" >= 0 AND \"PasswordResetEmailCount\" <= 3");

                            t.HasCheckConstraint("CK_AspNetUsers_PendingEmailConsistency", "(\"PendingEmail\" IS NULL AND \"NormalizedPendingEmail\" IS NULL AND \"PendingEmailExpiresAtUtc\" IS NULL) OR (\"PendingEmail\" IS NOT NULL AND \"NormalizedPendingEmail\" IS NOT NULL AND \"PendingEmailExpiresAtUtc\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActionTrace", b =>
                {
                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActivityLink", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.TeamActivity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActivityParticipant", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.TeamActivity", null)
                        .WithMany("Participants")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.TeamMembership", null)
                        .WithMany()
                        .HasForeignKey("TeamMembershipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActivityStrategy", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.TeamActivity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.Strategy", null)
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ActivityType", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.FormerMember", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.ImageFile", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.Strategy", null)
                        .WithMany()
                        .HasForeignKey("StrategyImageForStrategyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamLogoForTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.TeamMembership", null)
                        .WithMany()
                        .HasForeignKey("CreatedMembershipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EsportTeamManager.Domain.Entities.TeamRole", null)
                        .WithMany()
                        .HasForeignKey("ProposedTeamRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.LegalAcceptance", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.LegalDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("LegalDocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.MatchDetail", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.TeamActivity", null)
                        .WithOne("MatchDetail")
                        .HasForeignKey("EsportTeamManager.Domain.Entities.MatchDetail", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.Invitation", null)
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EsportTeamManager.Domain.Entities.OwnershipTransfer", null)
                        .WithMany()
                        .HasForeignKey("OwnershipTransferId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.OwnershipTransfer", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.TeamMembership", null)
                        .WithMany()
                        .HasForeignKey("InitiatorMembershipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.TeamMembership", null)
                        .WithMany()
                        .HasForeignKey("RecipientMembershipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.Strategy", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.TeamMembership", null)
                        .WithMany()
                        .HasForeignKey("CreatedByMembershipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.Team", b =>
                {
                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.TeamActivity", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.TeamMembership", null)
                        .WithMany()
                        .HasForeignKey("CreatedByMembershipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.TeamMembership", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.FormerMember", null)
                        .WithMany()
                        .HasForeignKey("FormerMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Domain.Entities.TeamRole", null)
                        .WithMany()
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.TeamRole", b =>
                {
                    b.HasOne("EsportTeamManager.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EsportTeamManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsportTeamManager.Domain.Entities.TeamActivity", b =>
                {
                    b.Navigation("MatchDetail");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
