<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="coverlet.collector" Version="6.0.4" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="10.0.10" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
	<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.13" />
	<PackageReference Include="xunit" Version="2.9.3" />
	<PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EsportTeamManager.Application\EsportTeamManager.Application.csproj" />
    <ProjectReference Include="..\EsportTeamManager.Domain\EsportTeamManager.Domain.csproj" />
    <ProjectReference Include="..\EsportTeamManager.Infrastructure\EsportTeamManager.Infrastructure.csproj" />
    <ProjectReference Include="..\EsportTeamManager.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>